#!/usr/bin/env groovy

// Shared libraries
@Library("cec-mobile-libraries") _
import com.oraclecorp.cec.mobile.*

// -----------------------------------------------------------------------------
// Custom steps for this branch
// -----------------------------------------------------------------------------

def doBuild() {
	println "*** in oce-angular-minimal-sample/doBuild()"

    unstash name: "workspace"
    
    // Make SSH creds available in case npm install needs to acccess internal git repo
    sshagent (credentials: [ Common.GIT_SSH_CREDENTIALS_ID ]) {
    sh """
      echo "[doBuild: "`pwd`"]"
      npm install
      mkdir -p INTERNAL/reports
      npm run lint -- --format checkstyle -o INTERNAL/reports/tslint.report || true
    """
    recordIssues(
        tool: checkStyle(pattern: 'INTERNAL/reports/tslint.report')
    )

    sh """
        ./node_modules/.bin/ng build --prod --base-href /samples/oce-angular-minimal-sample/
        ./INTERNAL/integration/scripts/dockerbuild.sh ${env.JOB_BASE_NAME} ${env.CCS_OPC_VERSION} ${env.BUILD_NUMBER}
        # Some build validation here?
        ./INTERNAL/integration/scripts/dockerpush.sh ${env.JOB_BASE_NAME} ${env.CCS_OPC_VERSION} ${env.BUILD_NUMBER}
    """
}

// -----------------------------------------------------------------------------
// Run the pipeline
// -----------------------------------------------------------------------------

// Map specifying a closure to be used for each build step
// If a step is not specified a defailt will be used
def config = [
	buildStep: this.&doBuild
]

devxPipeline(config)
